apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-consumer
  template:
    metadata:
      labels:
        app: redis-consumer
    spec:
      containers:
        - name: redis-consumer
          image: abhirockzz/redis-consumer
          imagePullPolicy: Always
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: credentials
            - name: REDIS_HOST
              value: <enter_redis_host>
            - name: REDIS_LIST
              value: <enter_redis_list>
